name: Python CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v6
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14

      - name: Install dependencies
        run: |
          pip install uv
          make install

      - name: Run linter and Pytest
        run: |
          make check
        env:
          TEST_BASE_DB_URL: postgres://admin:admin@localhost:5432/test

      - name: Run test coverage
        run: |
          make test-coverage

      - name: SonarQubeScan
        uses: SonarSource/sonarqube-scan-action@v7
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=K-Mickey_python-project-83
            -Dsonar.organization=kokmickey
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.sources=page_analyzer
            -Dsonar.tests=tests
